name: Docker Images

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build-and-push-molecule:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build terraform image
        working-directory: .
        run: docker-compose build molecule
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME  }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD  }}
      - name: Push docker image
        working-directory: .
        run: docker-compose push